//go:build darwin

// launchd_darwin.go implements macOS's autostart mechanism
// (dev_docs/production-runtime/PLATFORM_NOTES.md §3.1): a launchd user
// agent, chosen over Login Items because a plist + one `launchctl` call
// works for a bare CLI with no app bundle, no Objective-C/Swift call
// and no Automation permission prompt.
//
// STATUS: PARTLY VERIFIED ON HARDWARE (macOS 26.6, Apple Silicon,
// 2026-08-23). This file was originally authored blind from a Linux dev
// box; the split below records exactly which claims have since been
// exercised on a real Mac and which have NOT, in the same spirit as
// desktop/README.md's honesty table. Do not promote a row without
// running the thing.
//
//	| | |
//	|---|---|
//	| The plist's exact XML (launchdPlistContent, autostart.go)           | unit-tested, byte for byte, both shapes |
//	| `launchctl bootstrap`/`bootout`/`print` actually invoked            | VERIFIED — enable/disable/enable round-tripped, `launchctl print` shows the job with the expected program and `state = running` |
//	| enable-twice idempotency (exactly one plist, one job)               | VERIFIED |
//	| disable removes everything enable created (plist + loaded job)      | VERIFIED — plist gone, `launchctl print` reports "Could not find service", runtime stopped, config.json cleared |
//	| The bundle-attributed plist runs and resolves the same state dir    | VERIFIED — the runtime started from /Applications/Dexel.app/Contents/MacOS/"Dexel Runtime" (and, before the rename, .../dexel-server) loaded the same state.db under ~/Library/Application Support/dexel |
//	| Load at ACTUAL login (as opposed to bootstrap in a live session)    | never observed |
//	| KeepAlive/ProcessType behaviour under a real crash                  | never observed |
//	| The NAME in System Settings follows the exec'd file's name          | VERIFIED BY THE OWNER — the pane read "dexel-server" after the program moved into the bundle, having read "dexel" before; that is what the rename to "Dexel Runtime" acts on (PLATFORM_NOTES.md §3.1.1) |
//	| That the pane now reads "Dexel Runtime"                             | NOT VERIFIABLE FROM HERE — needs a human looking at the pane, and BTM caches; see PLATFORM_NOTES.md §3.1.1 |
//	| The ICON and the "unidentified developer" subtitle                  | NOT FIXABLE without a paid Developer ID — settled, see PLATFORM_NOTES.md §3.1.1 |
package autostart

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strconv"
)

func launchdGUIDomain() (string, error) {
	u, err := user.Current()
	if err != nil {
		return "", fmt.Errorf("determine current user: %w", err)
	}
	uid, err := strconv.Atoi(u.Uid)
	if err != nil {
		return "", fmt.Errorf("parse uid %q: %w", u.Uid, err)
	}
	return fmt.Sprintf("gui/%d", uid), nil
}

// enablePlatform writes the plist and loads it. PLATFORM_NOTES.md
// §3.1's primary command is `launchctl bootstrap`, with `load -w` as
// the fallback for older macOS — both are attempted, bootstrap first,
// and bootstrap's "already bootstrapped" case is tolerated (idempotent
// enable), since bootstrap errors if the label is already loaded.
//
// ProgramArguments[0] is NOT necessarily exePath, and the plist may
// carry an AssociatedBundleIdentifiers key: launchdProgram (autostart.go)
// decides both, preferring an installed .app bundle's own executable so
// macOS has a bundle to attribute the background item to. Read that
// function's section comment for the mechanism, the evidence behind each
// half of it, and — importantly — what it does NOT fix. That decision is
// pure and unit-tested; everything filesystem- and launchctl-shaped
// stays here.
//
// ONLY those two things change. The plist is still generated by the one
// launchdPlistContent — so StandardOutPath/StandardErrorPath, RunAtLoad,
// ProcessType=Background and the load-bearing
// KeepAlive.SuccessfulExit=false ("restart if it crashed, do not restart
// after a clean `dexel stop`") are byte-identical either way, and the
// `runtime` argument is still `runtime`, because launchd is still the
// supervisor that owns stdio.
func enablePlatform(exePath, logPath string, opts Options) (Result, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return Result{}, fmt.Errorf("resolve home dir: %w", err)
	}
	program, bundleID, note := launchdProgram(exePath, launchdBundleCandidates(home), isExecutableFile, opts)

	path := launchdPlistPath(home)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return Result{}, fmt.Errorf("create LaunchAgents dir: %w", err)
	}
	if err := os.WriteFile(path, []byte(launchdPlistContent(program, logPath, bundleID)), 0o644); err != nil {
		return Result{}, fmt.Errorf("write plist: %w", err)
	}

	domain, err := launchdGUIDomain()
	if err != nil {
		return Result{}, err
	}

	if err := runLaunchctl("bootstrap", domain, path); err != nil {
		// bootstrap fails if the label is already loaded (an idempotent
		// second `enable`) — reconcile by bootout-then-bootstrap rather
		// than trusting a substring match on its error text, which
		// varies by macOS version.
		//
		// This is also the path that matters when `enable` is re-run to
		// MOVE the job from the bare binary to the bundle: the plist on
		// disk has already been rewritten above, but launchd is still
		// running the old ProgramArguments from the copy it loaded, so
		// the bootout/bootstrap round-trip is what actually makes the
		// new program take effect rather than sitting inert on disk
		// until the next login.
		_ = runLaunchctl("bootout", domain+"/"+launchdLabel)
		if err := runLaunchctl("bootstrap", domain, path); err != nil {
			// Older macOS: bootstrap isn't the right verb at all.
			if err := runLaunchctl("load", "-w", path); err != nil {
				return Result{}, fmt.Errorf("launchctl bootstrap/load: %w", err)
			}
		}
	}
	return Result{Mechanism: MechanismLaunchd, Program: program, Note: note}, nil
}

// isExecutableFile is launchdProgram's real-filesystem predicate: a
// regular file (never a directory or symlink-to-nothing) with at least
// one execute bit. Both halves matter — an .app directory that exists
// with none of bundleServerExecutables inside it, or a zero-permission
// leftover, must not be baked into a plist as a program launchd will
// fail to spawn at every login.
func isExecutableFile(path string) bool {
	info, err := os.Stat(path)
	if err != nil || !info.Mode().IsRegular() {
		return false
	}
	return info.Mode().Perm()&0o111 != 0
}

// disablePlatform unloads the job (bootout, falling back to unload -w
// on older macOS) and removes the plist. Idempotent: if the plist is
// already absent there is nothing to unload or remove.
func disablePlatform() error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("resolve home dir: %w", err)
	}
	path := launchdPlistPath(home)
	if _, statErr := os.Stat(path); statErr != nil {
		if os.IsNotExist(statErr) {
			return nil
		}
		return statErr
	}

	domain, err := launchdGUIDomain()
	if err != nil {
		return err
	}
	bootoutErr := runLaunchctl("bootout", domain+"/"+launchdLabel)
	if bootoutErr != nil {
		bootoutErr = runLaunchctl("unload", "-w", path)
	}
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove plist: %w", err)
	}
	return bootoutErr
}

// queryPlatform reports `launchctl print <domain>/<label>`'s exit code
// plus the plist's existence, exactly as PLATFORM_NOTES.md §3.1
// specifies.
func queryPlatform() (Status, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return Status{}, fmt.Errorf("resolve home dir: %w", err)
	}
	path := launchdPlistPath(home)
	if _, statErr := os.Stat(path); statErr != nil {
		if os.IsNotExist(statErr) {
			return Status{}, nil
		}
		return Status{}, statErr
	}
	domain, err := launchdGUIDomain()
	if err != nil {
		return Status{}, err
	}
	printErr := runLaunchctl("print", domain+"/"+launchdLabel)

	// Report the program the plist ACTUALLY names, read back off disk.
	// `enable` may have pointed it at an .app bundle's executable rather
	// than the bare binary (see launchdProgram), and the user may have
	// hand-edited it since — so `status` asks the file, exactly as it
	// asks launchctl rather than trusting config.json. An unreadable or
	// unrecognised plist reports "unknown", never a guess.
	program := "unknown (could not read ProgramArguments from the plist)"
	if data, readErr := os.ReadFile(path); readErr == nil {
		if p := launchdPlistProgram(string(data)); p != "" {
			program = p
		}
	}

	return Status{
		Mechanism: MechanismLaunchd,
		Active:    printErr == nil,
		Detail: fmt.Sprintf("launchd: plist present at %s, launchctl print %s, program %s",
			path, boolWord(printErr == nil), program),
	}, nil
}

func runLaunchctl(args ...string) error {
	out, err := exec.Command("launchctl", args...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("launchctl %s: %w (%s)", args, err, bytes.TrimSpace(out))
	}
	return nil
}

func boolWord(b bool) string {
	if b {
		return "succeeded"
	}
	return "failed"
}
