// RENDER layer — the sound effects (SOUND-1, docs/ui-spec.md §13).
//
// Six tiny chiptune WAVs, generated by tools/gen_sounds.py, served from
// /sounds/*.wav by the same embedded FileServer that served this page
// (app/embed.go), played through one WebAudio graph. This module is the ONLY
// place in the frontend that touches an AudioContext, and it sends no
// ClientAction — it belongs in the render layer for the same reason
// render/scene.ts does: given the state the server sent, it produces output
// the user perceives, and it decides nothing.
//
// WHAT MAKES A SOUND, AND WHAT DELIBERATELY DOES NOT. Six moments, all of
// them either a real server event or a click the user just made:
//
//   sprint_complete   a `flash{kind:"sprint"}` — the payday
//   session_complete  a kept session's `sessionComplete` — the card moment
//   react_*           the four SCENE-REACTIONS clicks (dev/monitor/
//                     beverage/buddy), one voice each
//
// There is no typing sound, no ambient loop and no UI click. That is a
// design decision, not an omission: dexel sits on a working developer's
// desk all day, and a companion that chirps on every keystroke or ticks on
// every menu open is a companion that gets muted on day one — at which
// point the six moments that were worth hearing are gone too. See
// tools/gen_sounds.py's docstring for the same argument from the generator's
// side, including why the optional UI tick was dropped.
//
// =========================================================================
// THE AUTOPLAY POLICY, which is the whole reason this file is not ten lines
// =========================================================================
//
// Browsers refuse to let a page make noise until the user has interacted
// with it. Concretely: an AudioContext constructed before any user gesture
// starts in state "suspended", and resume() on it REJECTS (or silently stays
// suspended) until a gesture has happened. Anything played into a suspended
// context is inaudible.
//
// dexel's six moments split cleanly across that line, and the split is not
// symmetrical:
//
//   - The four reactions ARE gestures. They arrive inside a `click`
//     handler, which is precisely when a context may be created and
//     resumed. So the first click both unlocks audio and plays its own
//     sound.
//
//   - The two completions are NOT. A sprint completes because the user was
//     typing in their EDITOR — dexel's window may not have been clicked
//     since the page loaded, or ever. This is the ordinary case, not an
//     edge case, and it is the one a naive implementation gets wrong by
//     throwing an unhandled rejection into the console on the app's
//     happiest moment.
//
// So the contract here is: a locked context is a NORMAL state and produces
// SILENCE, never an error. play() on a locked context asks the browser to
// resume (harmless, and it succeeds on the rare occasion the page already
// has a gesture the listener below missed), swallows the rejection, and
// gives up after a bounded quarter-second (see GRACE_MS). No throw, no
// console noise, and no queue of sounds waiting to stampede out the moment
// the user finally clicks — a jingle for a sprint that finished twenty
// minutes ago is worse than no jingle.
//
// A second, smaller consequence: DECODING is also deferred to the first
// gesture. decodeAudioData needs a context, so nothing can be decoded before
// one exists; warming all six then means the first REAL sound never waits on
// a fetch.
import * as store from '../state/store';

// name -> file under /sounds/. The names are this module's API (play() takes
// one) and the files are tools/gen_sounds.py's manifest; the two lists are
// the same six, and the generator's own manifest deletes any WAV it does not
// claim, so a file that disappears here fails as a 404 at warm time rather
// than as a silent nothing at play time.
const SOUND_FILES = {
  sprintComplete: 'sprint_complete.wav',
  sessionComplete: 'session_complete.wav',
  reactDev: 'react_dexel.wav',
  reactMonitor: 'react_monitor.wav',
  reactBeverage: 'react_beverage.wav',
  reactBuddy: 'react_buddy.wav'
} as const;

export type SoundName = keyof typeof SOUND_FILES;

const SOUND_PREFIX = '/sounds/';

// Master gain. One constant, applied to every voice, because the RELATIVE
// balance between the six is already fixed where it belongs — in
// tools/gen_sounds.py's per-sound peak declarations (the jingles at -12 dBFS,
// the reactions between -18 and -15). Mixing here as well would mean two
// places deciding how loud a mug is, which is how they drift.
const MASTER_GAIN = 0.5;

// The one graph, built on first use. `ctx === null` means "not created yet";
// `unavailable` means "cannot be created at all" (no WebAudio in this
// browser, or the constructor threw), which is remembered so a page with no
// audio support does not retry on every single click for the rest of the
// session.
let ctx: AudioContext | null = null;
let master: GainNode | null = null;
let unavailable = false;

// Decoded buffers by sound name, plus the set of names already being
// fetched. Both are keyed by name rather than URL because the URL is derived
// and the name is the contract.
const buffers: Partial<Record<SoundName, AudioBuffer>> = {};
const fetching: Partial<Record<SoundName, true>> = {};

// AudioContext is still prefixed on older WebKit. Read off `window` through a
// narrow local type rather than `any` so the rest of this file stays typed.
interface AudioWindow {
  AudioContext?: typeof AudioContext;
  webkitAudioContext?: typeof AudioContext;
}

function audioContextCtor(): typeof AudioContext | undefined {
  const w = window as unknown as AudioWindow;
  return w.AudioContext || w.webkitAudioContext;
}

// Returns the live context, creating it on first call. Never throws: a
// browser without WebAudio, or one that refuses the constructor, leaves this
// module permanently and quietly inert — sound is a garnish, and no part of
// this app may fail because a garnish did.
function ensureContext(): AudioContext | null {
  if (ctx) return ctx;
  if (unavailable) return null;
  const Ctor = audioContextCtor();
  if (!Ctor) {
    unavailable = true;
    return null;
  }
  try {
    ctx = new Ctor();
  } catch (_err) {
    unavailable = true;
    return null;
  }
  master = ctx.createGain();
  master.gain.value = MASTER_GAIN;
  master.connect(ctx.destination);
  return ctx;
}

// Fetch + decode one sound into `buffers`. Idempotent and fire-and-forget:
// nothing awaits it, and a failure is swallowed for the same reason
// render/preload.ts swallows a failed sprite warm — a second, competing
// diagnostic for a missing asset helps nobody, and the sound is simply
// absent until (and if) a later attempt succeeds.
function loadSound(name: SoundName): void {
  if (buffers[name] || fetching[name]) return;
  const audio = ensureContext();
  if (!audio) return;
  fetching[name] = true;
  fetch(SOUND_PREFIX + SOUND_FILES[name])
    .then(function (res) {
      if (!res.ok) throw new Error(String(res.status));
      return res.arrayBuffer();
    })
    // decodeAudioData's promise form is what every browser this ships to
    // supports; the callback form is the ancient one and is not needed.
    .then(function (bytes) { return audio.decodeAudioData(bytes); })
    .then(function (buf) { buffers[name] = buf; })
    .catch(function () {
      // Allow a retry on a later play(): a transient fetch failure should
      // not silence one sound for the life of the page.
      delete fetching[name];
    });
}

// THE PREFERENCE GATE. Read from the server's `state` on every single play,
// never cached and never remembered locally — the same rule the Settings
// modal's toggles follow, and it is what makes a mute in a second tab, or a
// hand-edited config.json plus a restart, take effect here without this
// module knowing anything happened.
//
// `!== false` rather than `!!`: soundEnabled DEFAULTS ON (SOUND-1), so an
// absent field means "the user has never chosen" and the honest answer to
// that is the default. See wire.ts's ConfigView.soundEnabled.
function soundEnabled(): boolean {
  const state = store.getState();
  return !!state && !!state.config && state.config.soundEnabled !== false;
}

// initAudio installs the first-gesture hook and nothing else. Called once
// from main.ts, before anything can render.
//
// Both `pointerdown` and `keydown` count: this app is fully keyboard-driven
// (six single-key launchers), so a user who never touches the mouse must
// still be able to unlock audio — and a keypress is as much a user gesture
// as a click to every browser's autoplay policy.
//
// Both listeners are removed as soon as EITHER fires — not `once: true`,
// which would only retire the one that fired and leave the other waiting
// forever. The unlock is a single event, so a `done` latch plus two explicit
// removals is what actually expresses it.
//
// It does NOT create the context eagerly. A context created at load time
// starts suspended and stays that way, and on some platforms it also spins up
// an audio device for a page that may never make a sound — so creation waits
// for the gesture that can actually unlock it.
export function initAudio(): void {
  let done = false;
  function unlock(): void {
    if (done) return;
    done = true;
    window.removeEventListener('pointerdown', unlock, true);
    window.removeEventListener('keydown', unlock, true);
    const audio = ensureContext();
    if (!audio) return;
    // A context created inside a gesture is usually already "running", but
    // resume() is cheap, idempotent, and the documented way to be sure.
    if (audio.state !== 'running') { void audio.resume().catch(function () { /* stays locked */ }); }
    // Warm ALL SIX now, not just the one this gesture is about to play. The
    // two completion sounds are the ones that matter here: they fire on a
    // server event that will not wait for a fetch, and this is the only
    // moment before then at which decoding is possible at all.
    warmSounds();
  }
  // Capturing, on `window`, for the same reason render/interaction.ts's
  // guards are: an open native <dialog> is promoted out of #root's paint
  // order but is still in the document, and a click on a modal button is a
  // perfectly good unlocking gesture.
  window.addEventListener('pointerdown', unlock, true);
  window.addEventListener('keydown', unlock, true);
}

// Fetch + decode every sound. Exported for symmetry with render/preload.ts's
// warm* functions and called from the unlock path above; safe to call more
// than once (loadSound is idempotent per name).
export function warmSounds(): void {
  (Object.keys(SOUND_FILES) as SoundName[]).forEach(loadSound);
}

// THE GRACE WINDOW, and why it is not a queue.
//
// A sound can be un-playable for two reasons that both resolve on their own
// within a few milliseconds: the context was created inside the very gesture
// that is asking (resume() is asynchronous, so it can still read
// "suspended"), and the buffer is still decoding (decodeAudioData is
// asynchronous too, and the first gesture is the earliest moment decoding
// could have started at all).
//
// Without a grace window those two make the FIRST sound after a page load
// silent — click the mug, watch it hop, hear nothing, click again and it
// works. Measured, not theorised: a headless click lands ~15ms after its own
// pointerdown, which is not enough for six WAVs to decode.
//
// So an un-ready sound is re-attempted for up to GRACE_MS and then dropped
// for good. That is deliberately NOT a queue:
//
//   - it is bounded to a quarter of a second, well inside the 800-1000ms
//     reaction beat and the celebration bounce, so a sound that lands late
//     still lands ON its moment;
//   - it expires, so a sprint that completed while the page had no gesture
//     never fires twenty minutes later when the user finally clicks — the
//     dishonesty this codebase refuses (a jingle is a claim that something
//     just happened);
//   - the preference is re-read on every attempt, so muting during the
//     window silences it like anything else.
const GRACE_MS = 250;
const GRACE_POLL_MS = 30;

// Play one sound, or don't. Every refusal here is silent by design — this is
// exactly render/scene.ts's queueReact posture ("there is no error state for
// 'the room did not feel like it'"), and here it is load-bearing rather than
// stylistic, because the most common refusal (a locked context on a sprint
// completion, which the user's editor caused and dexel's window never saw)
// is a browser policy working correctly, not a fault.
export function play(name: SoundName): void {
  if (!soundEnabled()) return;
  if (!ensureContext()) return;
  attempt(name, Date.now() + GRACE_MS);
}

// One attempt, re-scheduling itself until `deadline`. Reads every gate fresh
// each time — the preference, the context state and the buffer — because all
// three can legitimately change inside the window.
function attempt(name: SoundName, deadline: number): void {
  const audio = ctx;
  if (!audio || !master) return;
  if (!soundEnabled()) return;
  const buf = buffers[name];
  if (audio.state === 'running' && buf) {
    // A BufferSource is single-use by specification — a fresh node per play,
    // connected to the shared master gain. Nothing needs to be disconnected
    // afterwards: a source that has finished is collectable once it has no
    // references, and it holds none of its own.
    const src = audio.createBufferSource();
    src.buffer = buf;
    src.connect(master);
    src.start();
    return;
  }
  if (Date.now() >= deadline) return;   // the moment has passed; never late
  if (audio.state !== 'running') {
    // Best effort: on a page that HAS had a gesture this succeeds and the
    // retry below is audible. On one that has not, it rejects, which is the
    // expected and documented outcome — hence the swallow.
    void audio.resume().catch(function () { /* still locked: stay silent */ });
  }
  loadSound(name);
  setTimeout(function () { attempt(name, deadline); }, GRACE_POLL_MS);
}
